version: '3.8'

services:
  mcp_servers:
    build:
      context: ./services/mcp_servers
      dockerfile: Dockerfile
    container_name: mcp_servers
    ports:
      - "9697:9697"
    env_file:
      - .env
    networks:
      - app-network


  mcp_client:
    build:
      context: ./services/mcp_client
      dockerfile: Dockerfile
    container_name: mcp_client
    ports:
      - "9696:9696"
    environment:
      - MCP_SERVER_URL=http://mcp_servers:9697/mcp
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - mcp_servers

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
