version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-pgvector
    environment:
      POSTGRES_DB: marahel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
