[project]
name = "marahel-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "anthropic>=0.50.0",
    "anyio>=4.9.0",
    "fastapi>=0.115.12",
    "filelock>=3.18.0",
    "jinja2>=3.1.6",
    "langchain-anthropic>=0.3.12",
    "langchain-community>=0.3.23",
    "langchain-openai>=0.3.14",
    "langchain-qdrant>=0.2.0",
    "langchain-text-splitters>=0.3.8",
    "langdetect>=1.0.9",
    "numpy>=2.2.5",
    "openai>=1.76.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pgvector>=0.3.6",
    "pillow>=11.2.1",
    "plotly>=6.0.1",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.4",
    "pymupdf>=1.25.5",
    "pypdf>=5.4.0",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
    "qdrant-client>=1.14.2",
    "requests>=2.32.3",
    "soundfile>=0.13.1",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.34.2",
    "aiofiles",
    "asyncpg",
    "async_timeout",
    "langchain>=0.3.24",
    "langchain-core>=0.3.56",
    "helicone-async>=1.0.6",
    "pandasai>=0.1.0",
    "langchain-cohere>=0.4.4",
    "langchain-experimental>=0.3.4",
    "tabulate>=0.9.0",
    "matplotlib>=3.10.3",
    "alembic>=1.15.2",
    "ollama>=0.5.1",
    "httpx>=0.28.1",
    "mcp>=1.9.4",
    "langchain-postgres>=0.0.13",
    "langgraph>=0.4.8",
    "psycopg-pool>=3.2.6",
    "langgraph-checkpoint-postgres>=2.0.21",
    "psycopg[binary,pool]>=3.2.9",
    "langgraph-checkpoint-sqlite>=2.0.10",
    "ruff>=0.12.2",
    "pyodbc>=5.2.0",
    "pymssql>=2.3.7",
    "streamlit>=1.47.0",
]
